id: Welcome
name: Welcome
systemPrompt: tasks/prompts/systemprompt.md
prompt: tasks/prompts/welcome.md
responseFormat: tasks/results/ToolVersion.json
responseProperty: tool
---
id: LocateREADME
name: Locate project README
prompt: tasks/prompts/locate_readme.md
responseFormat: tasks/results/Location.json
responseProperty: readme
tags:
  - readme_location
---
id: ProjectSummary
name: Project summary
prompt: tasks/prompts/project_summary.md
responseFormat: tasks/results/ProjectSummary.json
responseProperty: project
tags:
  - project_summary
---
id: BuildSystems
name: Detect used Build Systems
prompt: tasks/prompts/build_systems.md
responseFormat: tasks/results/BuildSystems.json
responseProperty: build
tags:
  - buildsystems
---
id: LocateModules
name: Locate code modules
prompt: tasks/prompts/locate_modules.md
responseFormat: tasks/results/Modules.json
responseProperty: modules
active: true
dependsOn:
  - buildsystems
  - project_summary
tags:
  - modules
---
id: ProgrammingLanguages
name: Programming languages
prompt: tasks/prompts/programming_languages.md
responseFormat: tasks/results/ProgrammingLanguages.json
responseProperty: programmingLanguages
dependsOn:
  - buildsystems
  - modules
tags:
  - programming_language
loopOn: /modules/modules
---
id: ModuleBuildfileAnalysis
name: Locate and analyse build files for module
prompt: tasks/prompts/module_analysis_buildfiles.md
responseFormat: tasks/results/ArchitectureEvaluation.json
responseProperty: build_analysis
dependsOn:
  - buildsystems
  - modules
  - programming_language
tags:
  - module_buildfile_analysis
loopOn: /modules/modules
---
id: ModulePurpose
name: Get a purpose for each module
prompt: tasks/prompts/module_purpose.md
responseFormat: tasks/results/ModulePurpose.json
responseProperty: purpose
active: true
dependsOn:
  - buildsystems
  - modules
  - programming_language
tags:
  - module_description
loopOn: /modules/modules
---
id: ModuleArchitecture
name: Get a description of the principle architecture for each module
prompt: tasks/prompts/module_architecture.md
responseFormat: tasks/results/ModuleArchitecture.json
responseProperty: architecture
active: true
dependsOn:
  - buildsystems
  - modules
  - programming_language
  - module_description
tags:
  - module_architecture
loopOn: /modules/modules
---
id: SBOMLocation
name: Location of SBOM
prompt: tasks/prompts/location_of_sbom.md
responseFormat: tasks/results/Location.json
responseProperty: sbom
tags:
  - sbom_location
---
id: LoadSBOM
name: Load SBOM
prompt: tasks/prompts/load_sbom.md
responseFormat: tasks/results/Result.json
responseProperty: sbom_loaded
dependsOn:
  - sbom_location
tags:
  - sbom
---
id: DependencyList
name: Get list of Dependencies
prompt: tasks/prompts/list_of_dependencies.md
responseFormat: tasks/results/DependencyList.json
responseProperty: dependencies
dependsOn:
  - sbom
tags:
  - dependencies
---
id: TechnologyStack
name: Description of the technology stack
prompt: tasks/prompts/description_of_stack.md
responseFormat: tasks/results/TechnologyStack.json
responseProperty: technologyStack
dependsOn:
  - sbom
tags:
  - technology_stack
---
id: LicenseEvaluation
name: Evaluation of used licenses
prompt: tasks/prompts/analysis_of_licenses.md
responseFormat: tasks/results/LicenseEvaluation.json
responseProperty: licenseEvaluation
dependsOn:
  - sbom
tags:
  - license_evaluation
---
id: FileStatistics
name: Collect some statics of some file types
prompt: tasks/prompts/file_statistics.md
responseFormat: tasks/results/FileStatistics.json
responseProperty: fileStatisticsPerProgrammingLanguage
dependsOn:
  - buildsystems
  - modules
  - programming_language
tags:
  - file_statistics
loopOn: /modules/modules
---
id: CodeSizeDistribution
name: Evaluate file count and line count statistics
prompt: tasks/prompts/code_size_distribution.md
responseFormat: tasks/results/ArchitectureEvaluation.json
responseProperty: code_size_distribution
dependsOn:
  - file_statistics
tags:
  - code_size_evaluation
---
id: ModuleSubdirectories
name: Identify the root directories for various artifacts
prompt: tasks/prompts/module_subdirectories.md
responseFormat: tasks/results/ModuleSubdirectories.json
responseProperty: subdirectories
dependsOn:
  - modules
  - programming_language
tags:
  - module_subdirectories
loopOn: /modules/modules

---
id: ModuleAnalysisReports
name: Collect analysis data per identified module
prompt: tasks/prompts/module_analysis_reports.md
responseFormat: tasks/results/ModuleAnalysisReports.json
responseProperty: analysisReports
dependsOn:
  - modules
  - programming_language
  - module_subdirectories
tags:
  - module_analysis_reports
loopOn: /modules/modules
---
id: ModuleCyclomaticComplexityEvaluation
name: Evaluate the measured cyclomatic complexity values of the module
prompt: tasks/prompts/module_cyclomatic_complexity_evaluation.md
responseFormat: tasks/results/ArchitectureEvaluation.json
responseProperty: cyclomaticComplexityEvaluation
dependsOn:
  - module_analysis_reports
tags:
  - module_cyclomatic_complexity_evaluation
loopOn: /modules/modules
